import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Multiplica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Hola Mundo</main>

      <footer>
        <p>creado por José Valdés</p>
      </footer>
    </div>
  );
}
